In [1]:
import qutip as qt
import numpy as np
import QMC as qmc
from pulsee import simulation as sim

In [2]:
rho_0, ops, ops_qubit, proj_ops, Id_S, Id = qmc.gen_initial_state(2)

In [3]:
Ix, Iy, Iz = ops
# Apply a \pi/2 pulse
rho_0 = sim.apply_rot_pulse(rho_0, np.pi/2, Iy)

In [4]:
# A pure state
'''Uncomment these to use the pure state instead'''
rho_0 = Ix.eigenstates()[1][0]
rho_0 = rho_0 * rho_0.dag()

In [5]:
rho_0

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25 -0.25  0.25]
 [-0.25  0.25  0.25 -0.25]
 [-0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]

In [6]:
measurement = np.array(qmc.perform_meas(rho_0))

# Find all the nonzero measurements
nonzero = np.nonzero(measurement)[0]

# Mask p perctange of them (set to 0)
p = .6
to_mask = np.random.choice(nonzero[1:], int(p*(len(nonzero)-1)), replace=False)
measurement[to_mask] = 0

In [7]:
# Reconstruct the measured state 
init_state = qmc.recover_state(measurement)

In [8]:
init_state

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25  0.    0.25]
 [-0.25  0.25  0.25  0.  ]
 [ 0.    0.25  0.25 -0.25]
 [ 0.25  0.   -0.25  0.25]]

In [9]:
rho_0

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25 -0.25  0.25]
 [-0.25  0.25  0.25 -0.25]
 [-0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]

In [10]:
np.round(qmc.fidelity(rho_0, init_state), 4)

0.866

In [11]:
rec_svt, rec_svt1 = qmc.svt(init_state, eps=1e-6, delta=1e-2, k0=5.23e-1, steps=20000, rank=1)

  0%|                                                                                | 1/20000 [00:00<03:59, 83.59it/s]


In [12]:
rec_svt1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.24999999 -0.24999999 -0.24999999  0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [ 0.24999999 -0.24999999 -0.24999999  0.24999999]]

In [13]:
rho_0

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25 -0.25  0.25]
 [-0.25  0.25  0.25 -0.25]
 [-0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]

In [14]:
np.round(qmc.fidelity(rho_0, rec_svt1), 4)

1.0

In [15]:
rec_admm, rec_admm1 = qmc.admm(init_state, eps=1e-10, rho=5, L=9e-2,)

  6%|████▎                                                                          | 55/1000 [00:00<00:07, 119.23it/s]


In [16]:
np.round(qmc.fidelity(rho_0, rec_admm1), 4)

1.0

In [17]:
rec_fista, rec_fista1 = qmc.fista_with_nesterov(init_state, eps=1e-10, L=9e-2)

  3%|██▎                                                                            | 29/1000 [00:00<00:04, 213.96it/s]


In [18]:
rec_fista1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25 -0.25  0.25]
 [-0.25  0.25  0.25 -0.25]
 [-0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]

In [19]:
rho_0

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25 -0.25  0.25]
 [-0.25  0.25  0.25 -0.25]
 [-0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]

In [20]:
np.round(qmc.fidelity(rho_0, rec_fista1), 4)

1.0